version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "KabOOm356"
    labels:
      - "gradle"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "KabOOm356"
    labels:
      - "github actions"
      - "dependencies"
