name: Reporter
author: KabOOm 356
website: https://dev.bukkit.org/projects/reporter
main: net.KabOOm356.Reporter.Reporter
version: 3.3.2 SNAPSHOT
softdepend: [Vault]
commands:
  report:
    aliases: [rreport, rep]
  respond:
    aliases: [rrespond, resp]
